name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    if: github.repository == 'pavel-jancik/ingress-default-backend' # Do not build forks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute TAG
        run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            currentDate=$(date +'%Y-%m-%d')
            echo "IMAGE_TAG=${currentDate}-${calculatedSha}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/s390x,linux/ppc64le
          push: true
          tags: |
            pjancik/ingress-default-backend:latest
            pjancik/ingress-default-backend:${{ env.IMAGE_TAG }}

